spring.application.name=ai-poc-1
# openai configuration
spring.ai.openai.api-key=sk-M8IB_mq6c0FYBOKfRUdxWOG1sLtRXvkcvOao0Hft1uT3BlbkFJQqGNGldLImFmCS_-pO7q4yhanc7SeWWFRNP3GYEKcA
#spring.ai.model.chat=ollama
#spring.ai.ollama.chat.options.model=llama3.2:latest